const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={caseId:crypto.randomUUID(),stage:1,six:{},senses:{},abcde:{},factors:{},generated:null,escalation:null};
const SIX=[["who","WHO","Who is involved? Yourself, others, parties, roles."],["what","WHAT","What happened or is proposed?"],["when","WHEN","When did it occur or when must action happen?"],["where","WHERE","Where did it take place or where does this land?"],["how","HOW","How did it unfold? What mechanism or method?"],["why","WHY","Why does this matter? What is the underlying cause?"]];
const SENSES=[["hearing","HEARING","Raw testimony — what was said or claimed."],["sight","SIGHT","Complete visible evidence field."],["touch","TOUCH","Directly verified records and contact."],["smell","SMELL","Contradictions, drift and anomalies."],["taste","TASTE","Consequence, fruit and coherence over time."]];
const ABCDE=[["A","EXACT LANGUAGE","Original words and exact names preserved?"],["B","WITNESS","Named and graded witness present?"],["C","CONTEXT","Scope, exclusions and time boundary defined?"],["D","CONSISTENCY","Sources, counts and timeline consistent?"],["E","ROOT MEANING","Original meaning and drift preserved?"]];
const FACTORS=[["intent","INTENT"],["authority","AUTHORITY"],["evidence","EVIDENCE"],["reversibility","REVERSIBILITY"],["mercy","MERCY"]];
const ESC=["PRESENCE — Don't Shatter","WITNESS — Record the Event","DISCERNMENT — Divide Claim and Carrier","RESPONSE — Calibrated Speak","ACTION — Structural Move","RESTORATION — Judgment and Repair"];
async function api(path,body){const r=await fetch(path,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:{},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||`HTTP ${r.status}`);return j}
function stages(){const names=["WITNESS","ALETHEIA","GATE","REGISTER","ESCALATE"];$("#steps").innerHTML=names.map((n,i)=>`<div class="step ${state.stage===i+1?"active":""}">${i+1} ${n}</div>`).join("");$$(".stage").forEach(x=>x.classList.toggle("active",+x.dataset.stage===state.stage))}
function build(){
 $("#six").innerHTML=SIX.map(([id,sym,q])=>`<div class="field"><label>${sym}</label><small>${q}</small><textarea data-six="${id}"></textarea></div>`).join("");
 $("#senses").innerHTML=SENSES.map(([id,l,d])=>rating(id,l,d,["STRONG","PARTIAL","WEAK","MISSING"],"sense")).join("");
 $("#abcde").innerHTML=ABCDE.map(([id,l,d])=>rating(id,`${id} — ${l}`,d,["CONFIRMED","PARTIAL","UNVERIFIED","MISSING"],"abcde")).join("");
 $("#factors").innerHTML=FACTORS.map(([id,l])=>`<div class="factor"><label>${l}</label><div class="factor-buttons">${[1,2,3,4,5].map(n=>`<button data-factor="${id}" data-value="${n}">${n}</button>`).join("")}</div></div>`).join("");
 $("#escalation").innerHTML=ESC.map((x,i)=>`<div class="escalation-card" data-escalation="${i}">L${i} · ${x}</div>`).join("");
 $$("[data-six]").forEach(x=>x.oninput=e=>state.six[e.target.dataset.six]=e.target.value);
 $$("[data-kind]").forEach(x=>x.onclick=()=>{const kind=x.dataset.kind,id=x.dataset.id;state[kind][id]=x.dataset.value;$$(`[data-kind="${kind}"][data-id="${id}"]`).forEach(b=>b.classList.remove("selected"));x.classList.add("selected");if(kind==="abcde"||kind==="senses")showAudit()});
 $$("[data-factor]").forEach(x=>x.onclick=()=>{state.factors[x.dataset.factor]=+x.dataset.value;$$(`[data-factor="${x.dataset.factor}"]`).forEach(b=>b.classList.remove("selected"));x.classList.add("selected");showGate()});
 $$("[data-escalation]").forEach(x=>x.onclick=()=>{state.escalation=+x.dataset.escalation;$$("[data-escalation]").forEach(b=>b.classList.remove("selected"));x.classList.add("selected")});
 stages();
}
function rating(id,label,desc,values,kind){return `<div class="rating"><label>${label}</label><small>${desc}</small><div class="rating-buttons">${values.map(v=>`<button data-kind="${kind}" data-id="${id}" data-value="${v}">${v}</button>`).join("")}</div></div>`}
function hardGate(){const missing=ABCDE.filter(([id])=>state.abcde[id]==="MISSING").map(x=>x[0]);const unknown=ABCDE.filter(([id])=>["UNVERIFIED"].includes(state.abcde[id])).map(x=>x[0]);if(missing.length)return {verdict:"HOLD",movement:"DRY_RUN_ONLY",reason:`Missing gates: ${missing.join(", ")}`};if(unknown.length)return {verdict:"UNKNOWN",movement:"NO_IRREVERSIBLE_ACTION",reason:`Unresolved gates: ${unknown.join(", ")}`};if(SENSES.some(([id])=>state.senses[id]==="MISSING"))return {verdict:"PARTIAL",movement:"REVERSIBLE_ONLY",reason:"A sensory channel is missing"};if(SENSES.every(([id])=>state.senses[id])&&ABCDE.every(([id])=>state.abcde[id]))return {verdict:"VERIFIED",movement:"GATE_ELIGIBLE",reason:"Hard gates confirmed"};return {verdict:"INCOMPLETE",movement:"HOLD",reason:"Complete all ratings"}}
function showAudit(){$("#auditVerdict").textContent=JSON.stringify(hardGate(),null,2)}
function showGate(){const vals=Object.values(state.factors);const total=vals.reduce((a,b)=>a+b,0);let verdict=vals.length<5?"INCOMPLETE":total>=22?"GATE OPEN":total>=17?"PROCEED WITH CAUTION":total>=12?"HOLD":"GATE CLOSED";$("#gateVerdict").textContent=`${verdict}\n${total}/25`}
async function save(type,payload){return api("/api/records",{record_type:type,case_id:state.caseId,status:"saved",raw:payload})}
$("#to2").onclick=async()=>{if(!SIX.every(([id])=>(state.six[id]||"").trim()))return alert("Complete all six questions");await save("witness_six_questions",state.six);state.stage=2;stages()}
$("#auditBtn").onclick=async()=>{if(!SENSES.every(([id])=>state.senses[id])||!ABCDE.every(([id])=>state.abcde[id]))return alert("Complete all evidence ratings");const r=await api("/api/audit/claim",{case_id:state.caseId,senses:state.senses,abcde:state.abcde,contradictions:[]});$("#auditVerdict").textContent=JSON.stringify(r.result,null,2);state.audit=r.result;state.stage=3;stages()}
$("#to4").onclick=async()=>{if(Object.keys(state.factors).length<5)return alert("Complete the permission gate");await save("permission_gate",state.factors);state.stage=4;stages()}
$("#generate").onclick=async()=>{const register=$("#register").value,receiver=$("#receiver").value,route=$("#route").value;const prompt=`Create the ${register.toUpperCase()} register response for a ${receiver} receiver. Preserve raw witness boundaries. Account:\n${SIX.map(([id,s])=>`${s}: ${state.six[id]}`).join("\n")}\nAletheia hard gate: ${JSON.stringify(hardGate())}\nPermission factors: ${JSON.stringify(state.factors)}`;$("#generated").textContent="ROUTING...";try{const r=await api("/api/route",{route,prompt,case_id:state.caseId,context:state});state.generated=r;$("#generated").textContent=JSON.stringify(r,null,2);await save("discernment_register",{register,receiver,route,result:r})}catch(e){$("#generated").textContent=e.message}}
$("#to5").onclick=()=>{state.stage=5;stages()}
$("#savePacket").onclick=async()=>{const packet={record_type:"final_case_packet",case_id:state.caseId,status:"sealed",raw_witness:state.six,senses:state.senses,abcde:state.abcde,hard_gate:hardGate(),permission_gate:state.factors,generated:state.generated,escalation_level:state.escalation};const r=await api("/api/records",packet);$("#finalResult").textContent=JSON.stringify(r,null,2)}
$("#exportPacket").onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`omega-case-${state.caseId}.json`;a.click()}
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".tab").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.tab).classList.add("active")})
async function status(){try{const r=await api("/api/status");$("#status").textContent=JSON.stringify(r,null,2);$("#connection").textContent="ONLINE";$("#connection").className="pill ok"}catch(e){$("#connection").textContent="OFFLINE";$("#connection").className="pill bad";$("#status").textContent=e.message}}
$("#refreshStatus").onclick=status;$("#refreshLedger").onclick=async()=>$("#ledgerOut").textContent=JSON.stringify(await api("/api/ledger?limit=50"),null,2);
$("#quickSend").onclick=async()=>{try{$("#quickOutput").textContent=JSON.stringify(await api("/api/route",{route:$("#quickRoute").value,prompt:$("#quickPrompt").value}),null,2)}catch(e){$("#quickOutput").textContent=e.message}}
$("#queueAgent").onclick=async()=>{const mirrors=[];if($("#mirrorDrive").checked)mirrors.push("drive");if($("#mirrorDropbox").checked)mirrors.push("dropbox");try{$("#agentOut").textContent=JSON.stringify(await api("/api/agent/queue",{task:$("#agentTask").value,context:{case_id:state.caseId},mirrors}),null,2)}catch(e){$("#agentOut").textContent=e.message}}
$("#refreshAgents").onclick=async()=>$("#agentList").textContent=JSON.stringify(await api("/api/agent/tasks"),null,2);
build();status();showAudit();showGate();
